# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_project_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='authors',
            new_name='author',
        ),
    ]
