# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0004_auto_20170930_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='textfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='{{user}}/{{pro}}/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
