# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0006_auto_20170930_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
