# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import user_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0007_auto_20170930_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='pro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textfile',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='document',
            field=models.FileField(upload_to=user_groups.models.user_directory_path),
        ),
    ]
