# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0008_auto_20170930_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='pro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
