# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0011_textfile_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
