# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0015_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
