# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='staff_only',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
