# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 19:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_auto_20171023_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, default=4, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(default='5', max_length=1, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
